language: R
cache: packages

jobs:
  include:
  - r: devel
  - r: release

notifications:
  email: false
  slack:
    rooms:
      - poissonconsulting:BKjfn7jsVh8zXTu2rq7BEQEb
    on_success: change
    on_failure: change
    
addons:
  apt:
    packages:
      - libudunits2-dev
