---
title: "About B.C. Ambient Water Quality Guidelines"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The British Columbia (B.C.) Ministry of Environment and Climate Change Strategy (ENV) develops [province-wide ambient water quality guidelines (WQG)](https://www2.gov.bc.ca/gov/content/environment/air-land-water/water/water-quality/water-quality-guidelines/approved-water-quality-guidelines) for substances or physical attributes that are important in both the fresh and marine surface waters of B.C. A WQG is a scientifically derived numerical concentration or narrative statement considered to be protective of designated values in ambient conditions. The WQGs are set after considering the scientific literature, results from toxicity tests, WQGs from other jurisdictions, and background conditions in B.C. 

The information below can be used to interpret the summary tables produced by this application.  For more information on the ambient water quality guidelines of British Columbia, please visit the [B.C. water quality guidelines website](https://www2.gov.bc.ca/gov/content/environment/air-land-water/water/water-quality/water-quality-guidelines/approved-water-quality-guidelines).

### Values
Ambient WQGs are derived for different water **values** including aquatic life (freshwater and marine), agriculture (livestock watering and irrigation), wildlife, source drinking water and recreation. 

### Media
WQGs can be derived for three **media**: water, sediment or tissue.  The tissue guidelines are for the concentration of the substance in the tissue of aquatic life or wildlife.  Wildlife – dietary guidelines are concentrations of the substance in fish or shellfish consumed by wildlife.  These are generally developed for substances that bioaccumulate. 

### Type
There are different **types** of water quality guidelines within each value:

- Aquatic life, agriculture and wildlife WQGs can be either long-term chronic or short-term acute:  

  - Long-term chronic WQGs are intended to be protective of all forms of aquatic life (all species, all life stages including multi-generational) from lethal and negative sub-lethal effects over indefinite exposures.
  
  - Short-term WQGs are intended to protect aquatic organisms against severe effects such as lethality due to short-term intermittent and/or transient exposures to contaminants (e.g. spill events or infrequent releases of short-lived/non-persistent substances).    
  
- Drinking WQGs can be either a maximum acceptable concentration or an aesthetic objective.  

- Recreation WQGs can be either for primary contact (e.g., swimming), secondary contact (e.g., canoeing, fishing) or an aesthetic objective.  

### Predicted Effect Level
Most WQGs are derived to be protective of the corresponding water value.  This is denoted by the “no effect” entry under the “predicted effect level” column on the summary table.  It is worthwhile noting that WQGs are our best estimate of a no-effect concentration, but these are only predictions based on laboratory testing of a small selection of species.  Extrapolating laboratory results to field conditions comes with a degree of uncertainty (for more information on the uncertainty of deriving WQGs, please see section 1.7 in the [B.C. Aquatic Life Derivation Protocol](https://www2.gov.bc.ca/assets/gov/environment/air-land-water/water/waterquality/water-quality-guidelines/derivation-protocol/bc_wqg_aquatic_life_derivation_protocol.pdf)). 

Sediment quality guidelines generally have two effect levels: no effect and probable effect.  The no effect guidelines are our best estimate of levels which are protective of aquatic life.  The probable effect level is a concentration that if exceeded will likely cause significant effects on aquatic life.  Concentrations that are between the no effect and probably effect concentrations are predicted to occasionally cause adverse biological effects.    

### Status
WQGs can be either, approved, approved but interim (denoted as “interim” in the summary table) or working.  Approved WQGs are those guidelines that were derived in B.C., consider the species and other factors unique to B.C., and are officially adopted as policy by ENV.  Interim guidelines are approved guidelines and are similar in all ways to approved guidelines except that fewer data were used to derive the guideline and therefore there is higher degree of uncertainty with these guidelines.  Interim guidelines can be updated to approved WQGs as additional data are generated by the scientific community.
Working WQGs are obtained from various Canadian provincial and federal jurisdictions (primarily the Canadian Council of the Ministers of the Environment or CCME), as well as the United States, Europe, and Australia/New Zealand, and from published scientific literature. Working WQGs provide benchmarks for those substances that have not yet been fully assessed and formally endorsed by the B.C. Ministry of Environment and Climate Change Strategy.

