---
title: "Water Quality Guideline"
output:
  html_document:
    toc: FALSE
    theme: null
    mathjax: null
params:
  use: NA
  table: NA
  refs: NA
  cvalues: NA
---
```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.align = "center", echo = FALSE, 
                      warning = FALSE, message = FALSE,
                      include = FALSE)
library(knitr)
library(kableExtra)
```

### `r params$use` 

```{r} 
x <- paste0(names(params$cvalues), ': ', params$cvalues, collapse = "<br>") 
```

##### `r x` 

```{r results = 'hide'}
df <- params$table %>%
  dplyr::mutate(Term = paste(Term, "Term"),
           Guideline = if_else(is.na(Guideline), NA_character_, 
                               paste(signif(Guideline, digits = 2), Units)),
           Equation = if_else(is.na(as.numeric(Equation)), Equation, NA_character_),
           Equation = paste0("$", Equation, "$")) %>%
    dplyr::select(Variable, Term, Guideline, Equation, Reference)

```
 
 
```{r, include = TRUE}
# knitr::kable(df, align = "c", booktabs = TRUE, escape = FALSE)
gt::gt(df, rowname_col = "Term", groupname_col = "Variable") %>%
  gt::fmt_missing(columns = gt::everything()) %>%
  cols_align(
    align = "center",
    columns = everything()
  ) %>%
  tab_style(
    style = cells_styles(text_size = px(13)),
    locations = cells_data(
      columns = vars(Guideline, Equation, Reference))
  ) %>%
  tab_footnote(
    "Canada 2014 blah blah",
    locations = cells_data(
      columns = vars(Reference),
      rows = Reference == "CANADA_2014"
    )
  ) %>%
  tab_footnote(
    "British Columbia 2015 blah blah",
    locations = cells_data(
      columns = vars(Reference),
      rows = Reference == "BC_2015"
    )
  )
```

### Download References 

```{r} 
refs <- paste0(paste0(names(params$refs), ".\\ "), params$refs, collapse = "<br>")
```

`r refs`

